apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange-test
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 1
    defaultRequest:
      memory: 256Mi
      cpu: 0.5
    max:
      cpu: 1
      memory: 512Mi
    min:
      cpu: 0.5
      memory: 256Mi
    type: Container
    